// <auto-generated />
using System;
using LicenseService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicenseService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113013656_130120261")]
    partial class _130120261
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicenseService.Entity.DeriveSecretAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("key_uuid")
                        .HasColumnType("uuid");

                    b.Property<string>("machine_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("public_key")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("secret_uuid")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("shared_secret")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("id");

                    b.HasIndex("key_uuid");

                    b.ToTable("secret");
                });

            modelBuilder.Entity("LicenseService.Entity.ECDHKeyPair", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("key_uuid")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("public_key")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("secret_key")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("id");

                    b.ToTable("key_pair");
                });

            modelBuilder.Entity("LicenseService.Entity.License", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("customer_site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("license")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("license_type")
                        .HasColumnType("integer");

                    b.Property<string>("machine_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("secret_id")
                        .HasColumnType("integer");

                    b.Property<Guid>("secret_uuid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("secret_id");

                    b.ToTable("license");
                });

            modelBuilder.Entity("LicenseService.Entity.DeriveSecretAudit", b =>
                {
                    b.HasOne("LicenseService.Entity.ECDHKeyPair", "key_pair")
                        .WithMany("secrets")
                        .HasForeignKey("key_uuid")
                        .HasPrincipalKey("key_uuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("key_pair");
                });

            modelBuilder.Entity("LicenseService.Entity.License", b =>
                {
                    b.HasOne("LicenseService.Entity.DeriveSecretAudit", "secret_key")
                        .WithMany("licenses")
                        .HasForeignKey("secret_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("secret_key");
                });

            modelBuilder.Entity("LicenseService.Entity.DeriveSecretAudit", b =>
                {
                    b.Navigation("licenses");
                });

            modelBuilder.Entity("LicenseService.Entity.ECDHKeyPair", b =>
                {
                    b.Navigation("secrets");
                });
#pragma warning restore 612, 618
        }
    }
}
