// <auto-generated />
using System;
using LicenseService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicenseService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118125011_180120261")]
    partial class _180120261
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicenseService.Entity.License", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("customer_site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("license")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("license_type")
                        .HasColumnType("integer");

                    b.Property<string>("machine_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("sign_key_uuid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("sign_key_uuid");

                    b.ToTable("license");
                });

            modelBuilder.Entity("LicenseService.Entity.SignKeyAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("sign_key_uuid")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("sign_priv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("sign_pub")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("id");

                    b.ToTable("sign_key");
                });

            modelBuilder.Entity("LicenseService.Entity.License", b =>
                {
                    b.HasOne("LicenseService.Entity.SignKeyAudit", "sign_key")
                        .WithMany("licenses")
                        .HasForeignKey("sign_key_uuid")
                        .HasPrincipalKey("sign_key_uuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sign_key");
                });

            modelBuilder.Entity("LicenseService.Entity.SignKeyAudit", b =>
                {
                    b.Navigation("licenses");
                });
#pragma warning restore 612, 618
        }
    }
}
