// <auto-generated />
using System;
using LicenseService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicenseService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicenseService.Entity.KeyPair", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("expire_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("key_uuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("private_key")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("public_key")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("id");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("LicenseService.Entity.License", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("customer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expire_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("key_uuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("license_type")
                        .HasColumnType("integer");

                    b.Property<string>("site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("key_uuid");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("LicenseService.Entity.License", b =>
                {
                    b.HasOne("LicenseService.Entity.KeyPair", "key_pair")
                        .WithMany("Licenses")
                        .HasForeignKey("key_uuid")
                        .HasPrincipalKey("key_uuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("key_pair");
                });

            modelBuilder.Entity("LicenseService.Entity.KeyPair", b =>
                {
                    b.Navigation("Licenses");
                });
#pragma warning restore 612, 618
        }
    }
}
